apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd
    instance: authentication.unbscholar.lib.unb.ca
    tier: auth
    uri: authentication.unbscholar.lib.unb.ca
  name: authentication-unbscholar-lib-unb-ca
  namespace: prod
spec:
  selector:
    matchLabels:
      uri: authentication.unbscholar.lib.unb.ca
  replicas: 1
  revisionHistoryLimit: 2
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: httpd
        instance: authentication.unbscholar.lib.unb.ca
        tier: auth
        uri: authentication.unbscholar.lib.unb.ca
    spec:
      nodeSelector:
        deployenv: prod
      containers:
        -
          name: authentication-unbscholar-lib-unb-ca
          readinessProbe:
            httpGet:
              path: /Shibboleth.sso/Status
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /Shibboleth.sso/Status
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /Shibboleth.sso/Status
              port: 80
            failureThreshold: 30
            periodSeconds: 10
          env:
            -
              name: DEPLOY_ENV
              value: prod
          image: "||DEPLOYMENTIMAGE||"
          imagePullPolicy: Always
          ports:
            -
              containerPort: 80
      priorityClassName: high-priority-services
      imagePullSecrets:
        -
          name: github-container-registry-auth
      restartPolicy: Always
